app:
  datasource:
    url: jdbc:postgresql://localhost:5432/cabinetpro
    username: cabinetuser
    password: cabinetpass
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
logging:
  level:
    root: INFO
    com.cabinetpro.lite: DEBUG